### PR TITLE
Change Video-motion and Music to extensions, add translate

### PR DESCRIPTION
**Pull request by chexbox**
This _should_ convert the music and video blocks to be extensions. This'll add 2 new color categories (13: music, 14: video-motion).

### CODE REVIEW

**Comment by chexbox** [comment]
I was working on the translate extension when this was merged. We'll see if it works.

**Comment by ZenithRogue** [comment]
You should be able to merge and commit yourself. Give it a try

**Comment by chexbox** [comment]
2018-06-03-192402_786x88_scrot
It looks like I can't.

**Comment by ZenithRogue** [comment]
sorry about all that, try it now

**Pull request merged**
