### PR TITLE
Replace "secs" with "seconds" and replace "clear" (pen) with "erase all"

### LINKED ISSUE #2: "Clear" block, should be "Erase all"

### PR DESCRIPTION
**Pull request by andybrwr**
should close #2 and #4.

### CODE REVIEW

**Comment by ZenithRogue** [comment]
I'm going to merge this for now, but I will want to convert the old blocks into aliases of these. (trying to figure that part out)

**Comment by andybrwr** [comment]
why alias them?

**Comment by ZenithRogue** [comment]
I want them to be aliases so they will appear as the new blocks, rather than being undefined on old forum posts

**Comment by chexbox** [comment]
I think I know how to do this. I'll give it a try.

**Pull request merged**
