### PR TITLE
Alias obsolete 2.0 blocks to the 3.0 version

### PR DESCRIPTION
**Pull request by chexbox**
As in #6.

### CODE REVIEW

**Comment by ZenithRogue** [comment]
Did you check to make sure these aliases actually function, and appear correctly?

BTW, I invited you to this github organization

**Comment by chexbox** [comment]
No, I am working on setting up a better local code-base with my Apache server, as npm hasn't been working to well recently.

**Comment by ZenithRogue** [comment]
I am doing all my development of s3blocks on a free service called cloud9. It is web based, but it runs an Ubuntu VM. It has everything preconfigured for stuff like node, php, c++, python, etc

**Comment by chexbox** [comment]
If I can't get that to work I might be able to install node on my mac.

**Comment by ZenithRogue** [comment]
C9.io

**Comment by chexbox** [comment]
I'll give it a try. Since I don' have this set up, can you try running my branch locally?

**Comment by andybrwr** [comment]
idk how to run this

**Comment by ZenithRogue** [comment]
@ALinuxLover check out the development section of the readme

**Comment by andybrwr** [comment]
my node is broken, will fix later

**Pull request closed without merging**
